# Generated by Django 3.0.4 on 2020-03-29 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agw', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_name',
        ),
    ]
